version: '3'

services:
  dashboard:
    build: ./app
    volumes:
      - ./app:/usr/src/app
    ports:
      - 80:8050
    command:
      # gunicorn --worker-class gevent -b :8050 main:server
      # gunicorn -b :8050 --workers=1 --threads=4 test_main:server 
      gunicorn -b :8050 --workers=1 --threads=4 test_main:app 